print("Hi! What's your name?")
name1 = input()
print("What's your GPA?")
GPA1 = input()
print("Hi! What's your name?")
name2 = input()
print("What's your GPA?")
GPA2 = input()
print("Hi! What's your name?")
name3 = input()
print("What's your GPA?")
GPA = input()
print("Hi! What's your name?")
name4 = input()
print("What's your GPA?")
GPA4 = input()
average = (int(GPA1)*int(GPA2)*int(GPA3)*int(GPA4))/4
print("The Average GPA between the four of you is" + answer)